import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "getting-started",
    {
      type: "category",
      label: "Examples",
      items: [
        "examples/index",
        "examples/calibnet-workflow",
        "examples/vercel-ai-adapter",
      ],
    },
  ],
  apiSidebar: [
    {
      type: "autogenerated",
      dirName: "api",
    },
  ],
};

export default sidebars;
